package lime.graphics.opengl.ext;

@:keep
@:noCompletion class EXT_framebuffer_object
{
	public var FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_EXT = 0x8CD1;
	public var FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_EXT = 0x8CD0;
	public var FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET_EXT = 0x8CD4;
	public var FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_EXT = 0x8CD3;
	public var FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_EXT = 0x8CD2;
	public var FRAMEBUFFER_BINDING_EXT = 0x8CA6;
	public var FRAMEBUFFER_COMPLETE_EXT = 0x8CD5;
	public var FRAMEBUFFER_EXT = 0x8D40;
	public var FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT = 0x8CD6;
	public var FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT = 0x8CD9;
	public var FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT = 0x8CDB;
	public var FRAMEBUFFER_INCOMPLETE_FORMATS_EXT = 0x8CDA;
	public var FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_EXT = 0x8CD7;
	public var FRAMEBUFFER_INCOMPLETE_READ_BUFFER_EXT = 0x8CDC;
	public var FRAMEBUFFER_UNSUPPORTED_EXT = 0x8CDD;
	public var INVALID_FRAMEBUFFER_OPERATION_EXT = 0x0506;

	@:noCompletion private function new() {}
}